"""intial migration

Revision ID: 31043bb7b99d
Revises: 
Create Date: 2026-06-29 11:38:07.423443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31043bb7b99d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.add_column('companies', sa.Column('location', sa.String(), nullable=True))
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.drop_column('companies', 'location')
    op.create_table('student',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('student_id', name=op.f('student_pkey'))
    )
    # ### end Alembic commands ###
