"""users table added

Revision ID: 0c05b7755858
Revises: 250d9ca9979c
Create Date: 2026-07-01 15:10:13.402843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c05b7755858'
down_revision: Union[str, Sequence[str], None] = '250d9ca9979c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    # ### end Alembic commands ###
